version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build: ./relicweapons
    command: python relicweapons/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/static
      - ./media:/media
    ports:
      - "80:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - nginx_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static:
  media: