version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build: ./relicweapons
    command: gunicorn relicweapons.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
      build: ./nginx
      container_name: nginx_container
      volumes:
        - staticfiles:/app/static/
      ports:
        - 8008:80
      depends_on:
        - web

volumes:
  staticfiles: