version: '3'

services:
  web:
    # Берем Dockerfile из каталога app
    build:
       context: ./relicweapons
       dockerfile: Dockerfile
    # Запускаем сервер gunicorn
    command: gunicorn relicweapons.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    # Дожидаемся запуска db
    depends_on:
      - db
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_volume: