# Generated by Django 4.2.7 on 2023-11-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelicWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relic_type', models.CharField(max_length=100)),
                ('weapon_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='relics')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='relics')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('quest_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('relic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relics.relicweapon')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relics.reward')),
            ],
        ),
    ]
