# Generated by Django 4.2.7 on 2023-11-17 13:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='relicweapon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='relics/images/relicweapons'),
        ),
        migrations.AlterField(
            model_name='relicweapon',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='relics/images/relicweapons'),
        ),
    ]
