# Generated by Django 4.2.7 on 2023-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0002_alter_quest_description_alter_relicweapon_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relicweapon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
