# Generated by Django 4.2.7 on 2023-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0003_alter_relicweapon_icon_alter_reward_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relicweapon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='relics/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='relics/'),
        ),
    ]
