# Generated by Django 4.2.7 on 2023-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0004_alter_relicweapon_icon_alter_reward_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['step']},
        ),
        migrations.AlterField(
            model_name='relicweapon',
            name='text',
            field=models.TextField(),
        ),
    ]
