# Generated by Django 4.2.7 on 2023-11-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0005_alter_quest_options_alter_relicweapon_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='relic',
        ),
        migrations.AddField(
            model_name='quest',
            name='relic',
            field=models.ManyToManyField(to='relics.relicweapon'),
        ),
    ]
