name: CI

on:
    push:
      branches:
        - master

jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            script: |
              cd FFXIV-RELICWEAPONS/
              docker-compose -f docker-compose.prod.yml down -v
              git fetch --all
              git branch backup-master
              git reset --hard origin/master
              docker-compose -f docker-compose.prod.yml up -d --build
              docker-compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput
              docker-compose -f docker-compose.prod.yml exec web python manage.py loaddata data.json
