name: CI

on:
    push:
      branches:
        - master

jobs:
    fetch_new_code:
      name: Fetching new code
      runs-on: ubuntu-latest
      steps:
        - name: executing pull and fetch
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            script: |
              cd FFXIV-RELICWEAPONS/
              git fetch --all
              git branch backup-master
              git reset --hard origin/master
    compose1:
      name: Composing new docker
      runs-on: ubuntu-latest
      needs: fetch_new_code
      steps:
        - name: executing compose
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            script: |
              cd FFXIV-RELICWEAPONS/
              docker-compose -f docker-compose.prod.yml down -v
              docker-compose -f docker-compose.prod.yml up -d --build
    compose2:
      name: migrate etc
      runs-on: ubuntu-latest
      needs: compose1
      steps:
        - name: executing compose
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            script: |
              cd FFXIV-RELICWEAPONS/
              docker-compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput
              docker-compose -f docker-compose.prod.yml exec web python manage.py loaddata data.json
              docker-compose -f docker-compose.prod.yml exec web python manage.py collectstatic --noinput