name: CI

on:
    push:
      branches:
        - master

jobs:
    tests:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:13.10
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: postgres
            ports:
              - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8==6.0.0 flake8-isort==6.0.0
            pip install -r ./relicweapons/requirements.txt
        - name: Test with flake8
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            DB_HOST: 127.0.0.1
            DB_PORT: 5432
          run: |
            python -m flake8 relicweapons/

    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            script: |
              cd FFXIV-RELICWEAPONS/
              git pull origin master
              docker-compose up --build -d
